export const adaptFilm = (film) => ({
  id: film.id,
  title: film.name,
  posterSrc: film.poster_image,
  previewSrc: film.preview_image,
  backgroundSrc: film.background_image,
  backgroundColor: film.background_color,
  videoSrc: film.video_link,
  previewVideoSrc: film.preview_video_link,
  description: film.description,
  rating: film.rating,
  ratingNumber: film.scores_count,
  director: film.director,
  stars: film.starring,
  duration: film.run_time,
  genre: film.genre,
  released: film.released,
  isFavorite: film.is_favorite,
});
